// react/src/views/ProfileView.js
import { useDispatch, useSelector } from 'react-redux';
import { Carousel } from 'react-responsive-carousel';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import {
  Avatar,
  Card,
  CardActions,
  CardContent,
  Button,
  Typography,
  Grid,
} from '@mui/material';
import { clearToken } from '../store/authSlice';
import { useNavigate } from 'react-router-dom';

const ProfileView = () => {
  const dispatch = useDispatch();
  const user = useSelector((state) => state.auth.user);
  const navigate = useNavigate();

  const handleLogout = () => {
    dispatch(clearToken());
    navigate('/');
  };

  return (
    <>
      {user && (
        <Grid container spacing={2}>
          <Grid item xs={12} md={3}>
            <Card className="text-center" variant="outlined">
              <Avatar sx={{ width: 150, height: 150, mx: 'auto', mt: 4 }}>
                <img
                  src={user.avatar}
                  alt={user.name}
                  style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                />
              </Avatar>
              <CardContent className="text-left">
                <Typography variant="h6" component="div">
                  First Name:
                </Typography>
                <Typography variant="subtitle1">{user.first_name}</Typography>
                <Typography variant="h6" component="div">
                  Last Name:
                </Typography>
                <Typography variant="subtitle1">{user.last_name}</Typography>
                <Typography variant="h6" component="div">
                  Email:
                </Typography>
                <Typography variant="subtitle1">{user.email}</Typography>
              </CardContent>
              <CardActions>
                <Button color="primary" onClick={handleLogout}>
                  Logout
                </Button>
              </CardActions>
            </Card>
          </Grid>
          <Grid item xs={12} md={9}>
            <Card variant="outlined">
              <CardContent>
                {user.photos && user.photos.length > 0 ? (
                  <Carousel>
                    {user.photos.map((photo, index) => (
                      <img src={photo.url} alt={photo.name} key={index} />
                    ))}
                  </Carousel>
                ) : (
                  <Typography variant="body1">No photos available.</Typography>
                )}
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      )}
    </>
  );
};

export default ProfileView;

// vue/src/views/ProfileView.vue
<template>
  <v-container>
    <v-row v-if="user">
      <v-col
        cols="12"
        md="3"
      >
        <v-card
          class="text-center"
          flat
        >
          <v-avatar
            size="150"
            class="mx-auto mt-4"
          >
            <img
              :src="user.avatar"
              :alt="user.first_name"
              style="object-fit: cover; width: 100%; height: 100%;"
            >
          </v-avatar>
          <v-card-text class="text-left">
            <v-list>
              <v-list-item>
                <v-list-item-content>
                  <v-list-item-title>First Name:</v-list-item-title>
                  <v-list-item-subtitle>{{ user.first_name }}</v-list-item-subtitle>
                </v-list-item-content>
              </v-list-item>
              <v-list-item>
                <v-list-item-content>
                  <v-list-item-title>Last Name:</v-list-item-title>
                  <v-list-item-subtitle>{{ user.last_name }}</v-list-item-subtitle>
                </v-list-item-content>
              </v-list-item>
              <v-list-item>
                <v-list-item-content>
                  <v-list-item-title>Email:</v-list-item-title>
                  <v-list-item-subtitle>{{ user.email }}</v-list-item-subtitle>
                </v-list-item-content>
              </v-list-item>
            </v-list>
          </v-card-text>
          <v-card-actions>
            <v-spacer />
            <v-btn
              color="primary"
              @click="onLogout"
            >
              Logout
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-col>
      <v-col
        cols="12"
        md="9"
      >
        <v-card flat>
          <v-card-text>
            <v-carousel v-if="user.photos">
              <v-carousel-item
                v-for="(photo, index) in user.photos"
                :key="index"
              >
                <v-img
                  :src="photo.url"
                  :alt="photo.name"
                  aspect-ratio="1"
                  cover
                  class="bg-grey-lighten-2"
                />
              </v-carousel-item>
            </v-carousel>
            <v-row v-else>
              <v-col>
                <p>No photos available.</p>
              </v-col>
            </v-row>
          </v-card-text>
        </v-card>
      </v-col>
      <v-col
        cols="12"
      >
        <UploadForm />  
      </v-col>
    </v-row>
  </v-container>
</template>  
<script>
import { mapActions, mapGetters } from 'vuex'
import router from '../router'
import UploadForm from '../components/UploadForm.vue'

export default {
  components: {
    UploadForm
  },
  computed: {
    ...mapGetters('auth', ['user']),
  },
  methods: {
    ...mapActions('auth', ['logout']),
    onLogout(){
      this.logout()
      router.push('/')
    }
  }
}
</script>
