// react/src/views/SuccessView.js
import { useSelector } from 'react-redux';
import { Link } from 'react-router-dom';

const SuccessView = () => {
  const user = useSelector((state) => state.auth.user);

  return (
    <div>
      <h2>Hi {user?.first_name} Registration Successful!</h2>
      <p>
        Click here to show profile: <Link to="/profile">Go to Profile</Link>
      </p>
    </div>
  );
};

export default SuccessView;

// vue/src/views/SuccessView.vue
<template>
  <v-container>
    <v-row v-if="user">
      <v-col>
        <h4>Welcome {{ user.first_name }}</h4>
        <p>
          Click <router-link :to="{ name: 'profile' }"> here </router-link> to
          go to profile
        </p>
      </v-col>
    </v-row>
  </v-container>
</template>
<script>
import { mapGetters } from 'vuex';

export default {
  computed: {
    ...mapGetters('auth', ['user']),
  },
};
</script>
